---
driver:
  name: docker
  use_sudo: false
  # Uncomment this for docker-windows:
  # socket: npipe:////./pipe/docker_engine
  socket: tcp://127.0.0.1:2375

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: webserver
    driver:
      name: docker
      run_options: --net app_network --ip 192.168.30.10
      forward:
        - 80:8080
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default/webserver_test.rb
    attributes:
  - name: railsapp
    driver:
      name: docker
      run_options: --net app_network --ip 192.168.30.11
      forward:
        - 3000:3200
    run_list:
      - recipe[rvm::default]
      - recipe[railsapp::default]
    verifier:
      inspec_tests:
        - test/smoke/default/railsapp_test.rb
  - name: database
    driver:
      name: vagrant
      network:
      - ["forwarded_port", {guest: 5432, host: 25432}]
      - ["app_network", {ip: "192.168.30.12"}]
    run_list:
      - recipe[postgresql]
      - recipe[postgresql::server]
      - recipe[database::default]
    verifier:
      inspec_tests:
        - test/smoke/default/database_test.rb
