---
driver:
  name: docker
  use_sudo: false
  # Uncomment this for docker-windows:
  # socket: npipe:////./pipe/docker_engine
  socket: tcp://127.0.0.1:2375

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

# WebServer and Application suites (see Database in `database` cookbook)
suites:
  - name: webserver
    driver:
      name: docker
      forward:
        - 80:8080
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default/webserver_test.rb
    attributes:
  - name: railsapp
    driver:
      name: docker
      forward:
        - 3000:3200
    run_list:
      - recipe[rvm::default]
      - recipe[railsapp::default]
    verifier:
      inspec_tests:
        - test/smoke/default/railsapp_test.rb
